In [3]:
x <- c(1:10)
print(x)


 [1]  1  2  3  4  5  6  7  8  9 10


In [4]:
# check if number is of numeric
is.numeric(x)


[1] TRUE

In [6]:
class(x)


[1] "integer"

In [12]:
x <- c(1L:10L)
print(x)


 [1]  1  2  3  4  5  6  7  8  9 10


In [10]:
class(x)


[1] "integer"

In [13]:
5L / 2L


[1] 2.5

In [14]:
4L * 5L


[1] 20

In [15]:
class(5L / 2L)


[1] "numeric"

In [17]:
(4.7 * 2L)


[1] 9.4

In [25]:
x <- "Suman Paudel"


In [26]:
class(x)


[1] "character"

In [27]:
y <- factor(x)


In [28]:
class(y)


[1] "factor"

In [29]:
y


[1] Suman Paudel
Levels: Suman Paudel

In [39]:
gender <- factor(c("male", "female", "female", "male"))


In [40]:
typeof(gender)


[1] "integer"

In [41]:
attributes(gender)


$levels
[1] "female" "male"  

$class
[1] "factor"

In [42]:
unclass(gender)


[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"

In [45]:
gender


[1] male   female female male  
Levels: female male

In [46]:
levels(gender)


[1] "female" "male"

In [52]:
sample_data <- as.POSIXct("2023-03-29 06:30")


In [53]:
sample_data


[1] "2023-03-29 06:30:00 +0545"

In [54]:
class(sample_data)


[1] "POSIXct" "POSIXt"

In [55]:
as.numeric(sample_data)


[1] 1680050700

In [56]:
sample_data <- as.POSIXlt("2023-03-29 06:30")


In [57]:
sample_data


[1] "2023-03-29 06:30:00 +0545"

In [58]:
class(sample_data)


[1] "POSIXlt" "POSIXt"

In [59]:
?POSIXct


DateTimeClasses              package:base              R Documentation

_D_a_t_e-_T_i_m_e _C_l_a_s_s_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     Description of the classes '"POSIXlt"' and '"POSIXct"'
     representing calendar dates and times.

_U_s_a_g_e:

     ## S3 method for class 'POSIXct'
     print(x, tz = "", usetz = TRUE, max = NULL, ...)
     
     ## S3 method for class 'POSIXct'
     summary(object, digits = 15, ...)
     
     time + z
     z + time
     time - z
     time1 lop time2
     
_A_r_g_u_m_e_n_t_s:

x, object: an object to be printed or summarized from one of the
          date-time classes.

tz, usetz: for timezone formatting, passed to 'format.POSIXct'.

     max: numeric or 'NULL', specifying the maximal number of entries
          to be printed.  By default, when 'NULL',
          'getOption("max.print")' used.

  digits: number of significant digits for the computations: should be
          high enough to represent the least i

In [60]:
k <- TRUE


In [61]:
class(k)


[1] "logical"

In [62]:
is.logical(k)


[1] TRUE

In [63]:
k


[1] TRUE

In [65]:
2 == 3


[1] FALSE

In [71]:
"data" < "stat"


[1] TRUE

In [75]:
"c" < "d"


[1] TRUE

In [78]:
"car" < "cat"


[1] TRUE

In [80]:
?"data" == "data"


Comparison                package:base                 R Documentation

_R_e_l_a_t_i_o_n_a_l _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     Binary operators which allow the comparison of values in atomic
     vectors.

_U_s_a_g_e:

     x < y
     x > y
     x <= y
     x >= y
     x == y
     x != y
     
_A_r_g_u_m_e_n_t_s:

    x, y: atomic vectors, symbols, calls, or other objects for which
          methods have been written.

_D_e_t_a_i_l_s:

     The binary comparison operators are generic functions: methods can
     be written for them individually or via the 'Ops' group generic
     function.  (See 'Ops' for how dispatch is computed.)

     Comparison of strings in character vectors is lexicographic within
     the strings using the collating sequence of the locale in use: see
     'locales'.  The collating sequence of locales such as 'en_US' is
     normally different from 'C' (which should use ASCII) and can be
     surpr

In [82]:
"data" < "datb"


[1] TRUE

: 

In [3]:
x <- c(1:10)


In [5]:
x * 3


[1]  3  6  9 12 15 18 21 24 27 30

In [6]:
x / 4


[1] 0.25 0.50 0.75 1.00 1.25 1.50 1.75 2.00 2.25 2.50

In [7]:
sqrt(x)


[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

In [8]:
x^2


[1]   1   4   9  16  25  36  49  64  81 100

In [11]:
x <- 1:10
y <- -5:4


In [13]:
x <- matrix(1:9, ncol = 3, nrow = 3)


In [14]:
x


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [15]:
x * 3


[,1] [,2] [,3]
[1,] 3    12   21  
[2,] 6    15   24  
[3,] 9    18   27

In [16]:
x <- c(a = 1, b = 1)


In [24]:
x <- 10:1
y <- -4:5


In [25]:
any(x < y)


[1] TRUE

In [26]:
all(x < y)


[1] FALSE

In [27]:
nchar(y)


[1] 2 2 2 2 1 1 1 1 1 1

In [31]:
x[1:2]


[1] 10  9

In [32]:
x[c(1, 4)]


[1] 10  7

In [34]:
x <- 1:10


In [35]:
x


[1]  1  2  3  4  5  6  7  8  9 10

In [39]:
apropos("mea")


[1] ".colMeans"          ".rowMeans"          "colMeans"          
 [4] "influence.measures" "kmeans"             "mean"              
 [7] "mean.Date"          "mean.default"       "mean.difftime"     
[10] "mean.POSIXct"       "mean.POSIXlt"       "rowMeans"          
[13] "weighted.mean"

In [40]:
NA


[1] NA

In [41]:
NULL


NULL

In [42]:
# 7 not applicable
# 8 dont know
# 9 missing


In [47]:
?library("Amelia")


library                  package:base                  R Documentation

_L_o_a_d_i_n_g/_A_t_t_a_c_h_i_n_g _a_n_d _L_i_s_t_i_n_g _o_f _P_a_c_k_a_g_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'library' and 'require' load and attach add-on packages.

_U_s_a_g_e:

     library(package, help, pos = 2, lib.loc = NULL,
             character.only = FALSE, logical.return = FALSE,
             warn.conflicts, quietly = FALSE,
             verbose = getOption("verbose"),
             mask.ok, exclude, include.only,
             attach.required = missing(include.only))
     
     require(package, lib.loc = NULL, quietly = FALSE,
             warn.conflicts,
             character.only = FALSE,
             mask.ok, exclude, include.only,
             attach.required = missing(include.only))
     
     conflictRules(pkg, mask.ok = NULL, exclude = NULL)
     
_A_r_g_u_m_e_n_t_s:

package, help: the name of a package, given as a name or literal
   

In [50]:
x <- NULL


In [51]:
is.null(x)


[1] TRUE

In [52]:
is.null(NA)


[1] FALSE

In [53]:
is.null(NULL)


[1] TRUE

In [54]:
sampleValue = 10

GetArray


ERROR: Error in eval(expr, envir, enclos): object 'GetArray' not found


In [55]:
x <- 1:10


In [56]:
mean(x)


ERROR: Error in eval(expr, envir, enclos): object 'X' not found


In [58]:
x <- 10:1
y <- -4:5
q <- c("Hockey", "Football", "Baseball", "Curling", "Rugby", "Lacrosse", "Basketball", "Tennis", "Cricket", "Soccer")


In [59]:
df <- data.frame(x, y, q)


In [63]:
head(df, n = 5)


x  y  q       
1 10 -4 Hockey  
2  9 -3 Football
3  8 -2 Baseball
4  7 -1 Curling 
5  6  0 Rugby

In [64]:
library(magrittr)


In [67]:
a <- matrix(1:10, nrow = 5, ncol = 2)


In [68]:
a


[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [70]:
b <- matrix(1:10, nrow = 2, ncol = 5)


In [71]:
b


[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [81]:
a * b


ERROR: Error in a * b: non-conformable arrays


In [80]:
a %*% (b)


[,1] [,2] [,3] [,4] [,5]
[1,] 13   27   41    55   69 
[2,] 16   34   52    70   88 
[3,] 19   41   63    85  107 
[4,] 22   48   74   100  126 
[5,] 25   55   85   115  145

In [76]:
a * t(b)


[,1] [,2]
[1,]  1    12 
[2,]  6    28 
[3,] 15    48 
[4,] 28    72 
[5,] 45   100

In [84]:
a %*% t(b)


ERROR: Error in a %*% t(b): non-conformable arguments
